id: 208f47cf7d664e8580cee1a4becbc897
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_676-The_Dharani_Essence_of_Immeasurable_Longevity_and_Wisdom-v1
  language: bo
  author: ''
  volume: {}
